VERSION 0.7
FROM node:19-alpine
WORKDIR /app

base:
  COPY build.sh .
  RUN npm install -g typescript

copy-files:
  FROM +base
  COPY index.html .
  COPY output2/ output2/
  COPY package-lock.json .
  COPY package.json .
  COPY postcss.config.cjs .
  COPY public/ public/
  COPY src/ src/
  COPY tailwind.config.cjs .
  COPY tsconfig.json .
  COPY tsconfig.node.json .
  COPY vite.config.ts .
  COPY yarn.lock .

install-deps:
  FROM +copy-files
  RUN npm install

build:
  FROM +install-deps
  ARG VITE_RUST_SERVER=http://localhost:8000
  ARG VITE_GO_SERVER=http://localhost:8001
  ARG VITE_PYTHON_SERVER=http://localhost:8002
  ARG VITE_NODE_SERVER=http://localhost:8003
  RUN npm run build

all:
  BUILD +build