VERSION 0.7
FROM node:19
WORKDIR /app

deps:
  COPY package*.json ./
  RUN npm install -g typescript
  RUN npm ci
  COPY index.html .
  COPY output2/ output2/
  COPY postcss.config.cjs .
  COPY public/ public/
  COPY src/ src/
  COPY tailwind.config.cjs .
  COPY tsconfig.json .
  COPY tsconfig.node.json .
  COPY vite.config.ts .
  COPY yarn.lock .

build:
  FROM +deps
  ENV VITE_RUST_SERVER=http://localhost:8000
  ENV VITE_GO_SERVER=http://localhost:8001
  ENV VITE_PYTHON_SERVER=http://localhost:8002
  ENV VITE_NODE_SERVER=http://localhost:8003
  RUN npm run build

all:
  BUILD +build
