VERSION 0.7
FROM python:3.10
WORKDIR /app

deps:
  COPY requirements.txt .
  RUN python -m pip install --upgrade pip
  RUN pip install flake8 pytest
  RUN if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  COPY src/ src/

lint:
    FROM +deps
    RUN flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    RUN flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

test:
    FROM +deps
    RUN pytest

build:
    FROM +test
    COPY Dockerfile .
    COPY readme.txt .
    # Build the final application Docker image
    # Note: Earthly does not support building Docker images directly.
    # You can use `earthly export` to export the image and build it using Docker.

all:
    BUILD +lint
    BUILD +test
    BUILD +build
