name: GH-Actions-Only

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  node_service_build:
    environment: "Actions Demo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: "{{defaultContect}}examples/polyglot-repo/node_server"
          push: true
          tags: ezeev/earthly-node-example:gh-actions-only
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: examples/polyglot-repo/node_server/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: "19.x"
      - name: Node Service Build
        working-directory: examples/polyglot-repo/node_server
        run: npm install
      - name: Node Service Test
        working-directory: examples/polyglot-repo/node_server
        run: npm test