name: GH-Actions-Only

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
   react_service_build:
    environment: "Actions Demo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ""
          push: true
          tags: ezeev/earthly-react-example:gh-actions-only
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-react-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: "19.x"
      - name: React Setup
        run: >
          npm install -g typescript &&
          npm install
      - name: React Service Build
        run: >
          VITE_RUST_SERVER=http://localhost:8000
          VITE_GO_SERVER=http://localhost:8001
          VITE_PYTHON_SERVER=http://localhost:8002
          VITE_NODE_SERVER=http://localhost:8003
          npm run build