# Earthfile

# Use the desired Node.js version
FROM node:19

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
deps:
    RUN npm ci
    SAVE ARTIFACT node_modules/ AS LOCAL node_modules/

# Copy the rest of the application code
COPY src/ ./src
COPY quotes.txt ./

# Install Node.js dependencies
install-deps:
    COPY --from=deps +node_modules/ ./node_modules/

# Run tests
test:
    FROM +install-deps
    RUN npm test

# Build the application (assuming there's a build script in package.json)
build:
    FROM +install-deps
    RUN npm run build
    SAVE ARTIFACT dist/ AS LOCAL dist/

# Build the application image
app-image:
    FROM node:19
    COPY --from=build +dist/ ./dist
    COPY --from=install-deps +node_modules/ ./node_modules
    COPY src/ ./src
    COPY quotes.txt ./
    ENTRYPOINT ["node", "src/index.js"]
    SAVE IMAGE ezeev/earthly-node-example:gh-actions-only

# Push the application image
push:
    FROM +app-image
    PUSH ezeev/earthly-node-example:gh-actions-only
