# VERSION 0.7
# FROM node:19.5.0-buster-slim 
# WORKDIR /quote-client

# deps:
#   COPY index.html package.json tsconfig.json tsconfig.node.json postcss.config.cjs tailwind.config.cjs vite.config.ts yarn.lock .
#   COPY --dir public .
#   RUN yarn global add typescript
#   RUN yarn

# test:
#   FROM +deps
#   RUN ls public/
#   RUN echo TODO: Implement react tests here

# build:
#   FROM +deps
#   ARG --required base_url   
#   RUN VITE_RUST_SERVER=$base_url:8000 \
#     VITE_GO_SERVER=$base_url:8001 \
#     VITE_PYTHON_SERVER=$base_url:8002 \
#     VITE_NODE_SERVER=$base_url:8003 \
#     yarn build
#   SAVE ARTIFACT dist/ 

# docker:
#   FROM nginx:latest 
#   ARG --required tag
#   COPY +build/dist /usr/share/nginx/html/
#   EXPOSE 80 
#   SAVE IMAGE --push ezeev/earthly-react-example:$tag
VERSION 0.7
FROM node:19
WORKDIR /app

deps:
  COPY package*.json ./
  RUN npm install -g typescript
  RUN npm ci
  COPY index.html .
  COPY output2/ output2/
  COPY postcss.config.cjs .
  COPY public/ public/
  COPY src/ src/
  COPY tailwind.config.cjs .
  COPY tsconfig.json .
  COPY tsconfig.node.json .
  COPY vite.config.ts .
  COPY yarn.lock .

build:
  FROM +deps
  ENV VITE_RUST_SERVER=http://localhost:8000
  ENV VITE_GO_SERVER=http://localhost:8001
  ENV VITE_PYTHON_SERVER=http://localhost:8002
  ENV VITE_NODE_SERVER=http://localhost:8003
  RUN npm run build

all:
  BUILD +build
