name: Earthly Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install earthly
      run: |
        sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/earthly/earthly/main/install.sh)"

    - name: Run earthly +test
      run: earthly +test
